name: baasboxpolymer
description: A sample BaasBox SDK Polymer Dart application
dependencies:
    polymer: ">=0.12.0 <0.13.0"
    core_elements: ">=0.2.0 <0.3.0"
    paper_elements: ">=0.1.0 <0.2.0"
    baasbox: any
transformers:
- polymer:
    entry_points: web/baasboxpolymer.html
